export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_SUCCESS_MESSAGE = "AUTH_SUCCESS_MESSAGE";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_RESULT = "SET_AUTH_RESULT";

export const FETCH_MODELS_START = "FETCH_MODELS_START";
export const FETCH_MODELS_SUCCESS = "FETCH_MODELS_SUCCESS";
export const FETCH_MODELS_FAIL = "FETCH_MODELS_FAIL";

export const ADD_MODELS_START = "ADD_MODELS_START";
export const ADD_MODELS_SUCCESS = "ADD_MODELS_SUCCESS";
export const ADD_MODELS_FAIL = "ADD_MODELS_FAIL";

export const DELETE_MODELS_START = "DELETE_MODELS_START";
export const DELETE_MODELS_SUCCESS = "DELETE_MODELS_SUCCESS";
export const DELETE_MODELS_FAIL = "DELETE_MODELS_FAIL";

export const UPDATE_MODELS_START = "UPDATE_MODELS_START";
export const UPDATE_MODELS_SUCCESS = "UPDATE_MODELS_SUCCESS";
export const UPDATE_MODELS_FAIL = "UPDATE_MODELS_FAIL";

export const FETCH_VISITS_START = "FETCH_VISITS_START";
export const FETCH_VISITS_SUCCESS = "FETCH_VISITS_SUCCESS";
export const FETCH_VISITS_FAIL = "FETCH_VISITS_FAIL";

export const ADD_VISITS_START = "ADD_VISITS_START";
export const ADD_VISITS_SUCCESS = "ADD_VISITS_SUCCESS";
export const ADD_VISITS_FAIL = "ADD_VISITS_FAIL";

export const DELETE_VISITS_START = "DELETE_VISITS_START";
export const DELETE_VISITS_SUCCESS = "DELETE_VISITS_SUCCESS";
export const DELETE_VISITS_FAIL = "DELETE_VISITS_FAIL";

export const UPDATE_VISITS_START = "UPDATE_VISITS_START";
export const UPDATE_VISITS_SUCCESS = "UPDATE_VISITS_SUCCESS";
export const UPDATE_VISITS_FAIL = "UPDATE_VISITS_FAIL";